from pydantic import BaseModel, Field, EmailStr
from typing import Optional, List
from datetime import datetime
from uuid import UUID


# Supervisor Profile Schemas
class SupervisorProfileBase(BaseModel):
    pass


class SupervisorProfileCreate(SupervisorProfileBase):
    user_id: UUID


class SupervisorProfileUpdate(BaseModel):
    pass


class SupervisorProfileResponse(SupervisorProfileBase):
    id: UUID
    user_id: UUID
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


# Supervisor with User info
class SupervisorWithUser(SupervisorProfileResponse):
    full_name: Optional[str] = None
    email: str
    username: str
    is_active: bool

    class Config:
        from_attributes = True


# Supervisor Student Assignment Schemas
class SupervisorStudentAssignmentBase(BaseModel):
    notes: Optional[str] = None


class SupervisorStudentAssignmentCreate(SupervisorStudentAssignmentBase):
    supervisor_id: UUID
    student_id: UUID


class SupervisorStudentAssignmentResponse(SupervisorStudentAssignmentBase):
    id: UUID
    supervisor_id: UUID
    student_id: UUID
    assigned_at: datetime
    assigned_by: Optional[UUID] = None

    class Config:
        from_attributes = True


# Student info for supervisor's assigned students
class AssignedStudentInfo(BaseModel):
    id: UUID
    student_id: UUID  # Student profile id
    user_id: UUID
    full_name: Optional[str] = None
    email: str
    student_code: Optional[str] = None
    year_group: int
    class_name: Optional[str] = None
    notes: Optional[str] = None

    class Config:
        from_attributes = True


# Supervisor creation request (includes user creation)
# Password is auto-generated by the backend and sent via email
class SupervisorCreateRequest(BaseModel):
    email: EmailStr
    full_name: str
    timezone: str = "Europe/London"


# Supervisor list response
class SupervisorListResponse(BaseModel):
    id: UUID
    user_id: UUID
    full_name: Optional[str]
    email: str
    is_active: bool
    assigned_students_count: int = 0
    assigned_classes_count: int = 0

    class Config:
        from_attributes = True


# Bulk student assignment
class BulkStudentAssignment(BaseModel):
    supervisor_id: UUID
    student_ids: List[UUID]
    notes: Optional[str] = None


# Supervisor Class Assignment Schemas
class SupervisorClassAssignmentBase(BaseModel):
    is_primary: bool = False


class SupervisorClassAssignmentCreate(SupervisorClassAssignmentBase):
    supervisor_id: UUID
    class_id: UUID


class SupervisorClassAssignmentResponse(SupervisorClassAssignmentBase):
    id: UUID
    supervisor_id: UUID
    class_id: UUID
    assigned_at: datetime
    assigned_by: Optional[UUID] = None

    class Config:
        from_attributes = True


# Class info for supervisor's assigned classes
class SupervisorAssignedClassInfo(BaseModel):
    id: UUID
    name: str
    year_group: int
    academic_year: Optional[str] = None
    student_count: int = 0
    is_primary: bool = False

    class Config:
        from_attributes = True


# Bulk class assignment for supervisor
class SupervisorBulkClassAssignment(BaseModel):
    supervisor_id: UUID
    class_ids: List[UUID]
    is_primary: bool = False
