from pydantic import BaseModel, Field, EmailStr
from typing import Optional, List
from datetime import datetime
from uuid import UUID


# Teacher Profile Schemas
class TeacherProfileBase(BaseModel):
    specialization: Optional[str] = None
    is_head_teacher: bool = False


class TeacherProfileCreate(TeacherProfileBase):
    user_id: UUID


class TeacherProfileUpdate(BaseModel):
    specialization: Optional[str] = None
    is_head_teacher: Optional[bool] = None


class TeacherProfileResponse(TeacherProfileBase):
    id: UUID
    user_id: UUID
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


# Teacher with User info
class TeacherWithUser(TeacherProfileResponse):
    full_name: Optional[str] = None
    email: str
    username: str
    is_active: bool

    class Config:
        from_attributes = True


# Teacher Class Assignment Schemas
class TeacherClassAssignmentBase(BaseModel):
    is_primary: bool = False


class TeacherClassAssignmentCreate(TeacherClassAssignmentBase):
    teacher_id: UUID
    class_id: UUID


class TeacherClassAssignmentResponse(TeacherClassAssignmentBase):
    id: UUID
    teacher_id: UUID
    class_id: UUID
    assigned_at: datetime
    assigned_by: Optional[UUID] = None

    class Config:
        from_attributes = True


# Class info for teacher's assigned classes
class AssignedClassInfo(BaseModel):
    id: UUID
    name: str
    year_group: int
    academic_year: Optional[str] = None
    student_count: int = 0
    is_primary: bool = False

    class Config:
        from_attributes = True


# Teacher creation request (includes user creation)
# Password is auto-generated by the backend and sent via email
class TeacherCreateRequest(BaseModel):
    email: EmailStr
    full_name: str
    timezone: str = "Europe/London"
    specialization: Optional[str] = None
    is_head_teacher: bool = False


# Teacher list response
class TeacherListResponse(BaseModel):
    id: UUID
    user_id: UUID
    specialization: Optional[str]
    is_head_teacher: bool
    full_name: Optional[str]
    email: str
    is_active: bool
    assigned_classes_count: int = 0

    class Config:
        from_attributes = True


# Bulk class assignment
class BulkClassAssignment(BaseModel):
    teacher_id: UUID
    class_ids: List[UUID]
    is_primary: bool = False
